### ISSUE TITLE
pypi_update_check uses python 3.7 and above options in subprocess.run

### ISSUE THREAD

**Issue by kb1828** [Cisco-Talos/cvdupdate#24]
pypi_update_check uses python 3.7 and above option capture_output in subprocess.run which makes in incompatible with python 3.6. I am running 3.6.10

`  File "/usr/local/python3/lib/python3.6/site-packages/cvdupdate/cvdupdate.py", line 792, in check
    latest_version = str(subprocess.run([sys.executable, '-m', 'pip', 'install', '{}==random'.format('cvdupdate')], capture_output=True, text=True))
  File "/usr/local/python3/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
`

**Comment by micahsnyder** [comment]
Thanks for the report, will investigate right away!

**Comment by micahsnyder** [comment]
Ok this should fix it: https://github.com/Cisco-Talos/cvdupdate/pull/25 
I tested on 3.6 on centos, 3.8 on linux, and 3.9 on windows.

**Comment by micahsnyder** [comment]
I'll update PyPI with a new patch version right away.

**Comment by micahsnyder** [comment]
Ok it's published: https://pypi.org/project/cvdupdate/
Sorry about the trouble, thanks for the bug report!

**Comment by kb1828** [comment]
Thanks!
