### ISSUE TITLE
Cvd continues even if main signatures is missing

### ISSUE THREAD

**Issue by sl0m0ZA** [Cisco-Talos/cvdupdate#36]
If the main.cvd or dailt.cvd is missing, the update continues, but does not re-pull the daily or main. This has been addresses in the pull request at [https://github.com/Cisco-Talos/cvdupdate/pull/35](https://github.com/Cisco-Talos/cvdupdate/pull/35)

**Comment by micahsnyder** [comment]
Merged #35 today. Sorry it took so long!
