### ISSUE TITLE
update pypi version of cvdupdate to include patch for DNS TXT query issue 

### ISSUE THREAD

**Issue by dholiday-splunk** [Cisco-Talos/cvdupdate#42]
* the version in pypi is 1.0.2 -- [link](https://pypi.org/project/cvdupdate/#history)
* the current version, [with the patch for DNX TXT query issue](https://github.com/Cisco-Talos/cvdupdate/issues/10), is 1.1.0

Please push the latest stable build to pypi so users of `cvdupdate` can use pypi to get the patched version. 

ty 🍻  😃

**Comment by micahsnyder** [comment]
Thanks for the reminder! So sorry this sat for ages. I had this idea I'd figure out the windows compatibility issue, then got distracted... and... well... Anyways. Lesson learned. 

Just published: https://github.com/Cisco-Talos/cvdupdate/runs/6463631148?check_suite_focus=true
https://pypi.org/project/cvdupdate/

**Comment by dholiday-splunk** [comment]
w00t - ty!! 🍺

**Comment by dholiday-splunk** [comment]
FYI for anyone endeavoring to run `cvdupdate` inside a docker container and running into the DNS TXT query issue - if you're running a version that's been patched for the aforementioned and still seeing the issue, you can instruct `cvdupdate` to use google's DNS server `8.8.8.8` with an environment variable. 

I added the following to my docker file and that got things rolling 

`ENV CVDUPDATE_NAMESERVER="8.8.8.8"` 

Note that using the `--dns` argument when invoking `docker run` did not work. My hypothesis is that `cvdupdate` is looking to `/etc/resolv.conf` to determine where the DNS server is and that file is one that Docker will manipulate on container creation to ensure container networking is setup. 

🍺
