### ISSUE TITLE
Describe dependencies and provide ways of installing that doesn't need pip

### ISSUE THREAD

**Issue by hcgrove** [Cisco-Talos/cvdupdate#44]
This seems like a project that is very usable in larger installations, like ours. I guess we're not the only place that would like to setup our own mirror, but can't run `pip` on the server we would like to run it on.

Now I need to find out how to install this on our relevant server.

**Comment by micahsnyder** [comment]
The dependencies list is in `setup.py`: https://github.com/Cisco-Talos/cvdupdate/blob/main/setup.py#L23-L30

If you need, you can download the "built distribution" files from https://pypi.org/project/cvdupdate/#files and manually install them, for all of the dependencies and then for CVDUpdate.  Will this work for you?

**Comment by hcgrove** [comment]
I found that list of dependencies, but it is far from being an obvious place for that.

It's hard to find a link to pypi.org, especially if you don't know it. I guess those files might help, but it's probably easier to backport the linked ubuntu package.

**Comment by micahsnyder** [comment]
> I found that list of dependencies, but it is far from being an obvious place for that.

Fair point. I've been using Python too long and I take it for granted.  

We can add the list of dependencies to the readme and mention the pypi link as well, for reference if pip cannot be used to install the packages.
