### ISSUE TITLE
cvd update doesn't download safebrowsing.cvd files

### ISSUE THREAD

**Issue by svraogithub** [Cisco-Talos/cvdupdate#56]
I have installed cvdupdate using python pip installer. When I ran cvd update, it is downloading daily, main, bytecode cvd files but not safebrowsing.cvd files. Please help me if there a way to get it downloaded.
Thanks
Venkat

**Comment by micahsnyder** [comment]
I'm sorry to say that as a result of changes to the Google Safebrowsing terms of service, we no longer update the safebrowsing.cvd database.  
For details: https://blog.clamav.net/2020/06/the-future-of-clamav-safebrowsing.html
